name: Self-Hosted Runner Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted, dabou-macos, macOS, ARM64
    steps:
      - name: Run a command
        run: |
          echo "Self-hosted runner is working!"
          echo "OS Release information ..."
          cat /etc/redhat-release
          # yamllint disable-line rule:trailing-spaces
          echo "OS and arch ..."
          uname -a